### ISSUE TITLE
Invalid dependencies when adding the package to unity

### ISSUE THREAD

**Issue by ScottAndIrwinDev** [InteractiveScapeGmbH/TuioUnityClient#13]
Hi, so far I have been using the package by downloading it by hand and putting the code into the project, but I would like to use the unity package manager instead, however, it gives an error about the version of the textmeshpro dependency and can't be added.

> [Package Manager Window] Error adding package: https://github.com/InteractiveScapeGmbH/TuioUnityClient.git.
> Unable to add package [https://github.com/InteractiveScapeGmbH/TuioUnityClient.git]:
>   Package com.interactive-scape.tuio_client@https://github.com/InteractiveScapeGmbH/TuioUnityClient.git has invalid dependencies or related test packages:
>     com.unity.textmeshpro (dependency): Version '' is invalid. Expected a 'SemVer' compatible value.
> UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

I am using the latest version of Unity 6, maybe that has something to do with it.

Best regards!

**Comment by eqbic** [comment]
Hey. I could reproduced the issue (I did not test with unity 6). I did set the version for the dependency which fixed the problem. As soon as the PR is merged you can update/import it via the package manager.

**Comment by ScottAndIrwinDev** [comment]
Perfect! Thanks :D
