### ISSUE TITLE
Newtonsoft.Json library

### ISSUE THREAD

**Issue by ScottAndIrwinDev** [InteractiveScapeGmbH/TuioUnityClient#17]
Hello,
I have seen that the Newtonsoft.Json library is included in the source code of the repository.
I think it would be better to include it as a dependency in the package.json, since the current included version causes an error with some unity native libraries that already use this library as a dependency.

I have tested and the one included by unity does not cause any error.
![image](https://github.com/InteractiveScapeGmbH/TuioUnityClient/assets/162702970/0973e2aa-d7b2-4f0d-afbb-ba75c7330b34)

Best regards.

**Comment by eqbic** [comment]
Ah nice. I somehow missed that unity has newtonsoft package in its own registry. Could you do a pull request with your changes so I can merge them to the main branch?
