### ISSUE TITLE
Unique ID not working

### ISSUE THREAD

**Issue by ScottAndIrwinDev** [InteractiveScapeGmbH/TuioUnityClient#19]
Hello,

I have a problem with the Unique ID system for the mobile. In mid-July, the UniqueID demo scene worked perfectly, you scanned the qr, and when you put the device on the table, unity correctly detected the ID that appeared on the web.

Since then, we have integrated your system in our own webApp, but to my surprise when we went to test it today, Unity was not able to show the unique id that appears on the web.

Believing that it was a problem of our implementation, I went to test again the UniqueID scene and it does not work, we have tried multiple times but Unity is not able to show the ID shown on the web. The code is exactly the same so I guess it is some problem of the web-table connection. The problem is that I don't have access to this data exchange and I don't have the ability to try to debug these connections. I have checked that both the ROOM ID and the public server are well assigned as they were in the last test.

I would like to be able to access logs or similar of these connections to at least have a clue where the problem could be, although I don't know if it is possible.

Best regards, thanks.

**Comment by paul-peters** [comment]
Is this issue related to [Scape X Mobile Issue: SxmBridge Node FileNotFound Exception](https://github.com/InteractiveScapeGmbH/VL.TUIO/issues/1)?

Just asking, because both issues appeared at the same time and the issue here may also be related to a problem running the `ScapeXMqttDeviceBridge`.

**Comment by ScottAndIrwinDev** [comment]
I don't know, at least in Unity I'm not getting any kind of error and it seems that the SxmMqttBridge library loads correctly. 

Also, it seems that unity is communicating correctly with the table, since it appears in Unity the correct value of the Room ID assigned in the table configuration. 

It just never defines the correct udid when placing a phone with the webapp open, when a month ago the same example code was working.

I just realized, that maybe this Issue should go in the ScapeXMobileUnityExamples repository.

Sorry for the confusion, best regards.

**Comment by paul-peters** [comment]
Did you integerate this webApp: [sxm-web](https://github.com/InteractiveScapeGmbH/sxm-web) ?

Its important the the web-app sends the correct [state message](https://github.com/InteractiveScapeGmbH/sxm-web/blob/deffa79c9c418c3246cdceae6af5ba4dafff1fd9/src/device.ts#L46) to the topic `sxm\<roomId>\box` at the broker you entered next to the roomId which is used by the SxmMqttBridge. With the broker `wss://broker.hivemq.com:8884` and the roomId `test4g` you should see messages like this:

![image](https://github.com/user-attachments/assets/bef8315f-a0ff-424d-8886-9a50e62845f1)

**Comment by ScottAndIrwinDev** [comment]
I don't know why it happened, but after further testing it seems that now everything is working correctly. I don't know if there was some failure in the broker or what but with the same tests now it works fine. Let's hope it continues like this :D
